baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Project Portafolio"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/logo.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: false
  name: "Jesús Soto"
  namecolor: ffc107
  profession: "Economist"
  github: "https://github.com/jesoto"
  gitlab: false
  linkedin: "https://www.linkedin.com/in/jessoto/"
  twitter: false
  instagram: false
  facebook: false

  # About
  disable_about: false
  descripe_l1_person: "hello! I am Jesús, an economics student at the Faculty of Social Sciences of the Pontifical Catholic University of Peru.
 I am a proactive, persevering person, with analytical skills and motivated by continuous learning.
I am passionate about Data Science and anything related to technology "



  descripe_l2_person: "🎯 My goal is to develop my professional career in data science, being part of a company that allows me to apply everything I
   have learned so far and continue to grow both personally and professionally to achieve the best possible results."
  skills:
    - name: Python
      percentage: 90
    - name: Tableau
      percentage: 85
    - name: SQL
      percentage: 80
    - name: Machine learning
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "Interbank"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Portafolio Monitoring Intern"
      startdate: Jul 2021
      enddate: present
      featuredpoints:
        - point: Monitoring the product portofolio using risk index
        - point: Manipulate data to generate insights by Dashboards
        - point: Build a Credit Scoring model to know the profile of the defaults customers

  # Education
  disable_education: false
  education:
    - degree: "B. Economics"
      branch: "Social Sciences"
      university: "Pontifical Catholic University of Peru"
      startedyear: "2017"
      graduation: "2022"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "example@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
