baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Project Portafolio"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/logo.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: false
  name: "Jesús Soto"
  namecolor: ffc107
  profession: "Economist"
  github: "https://github.com/jesoto"
  gitlab: false
  linkedin: "https://www.linkedin.com/in/jessoto/"
  twitter: false
  instagram: false
  facebook: false

  # About
  disable_about: false
  descripe_l1_person: "hello! I am Jesús, an economics student at the Faculty of Social Sciences of the Pontifical Catholic University of Peru.
 I am a proactive, persevering person, with analytical skills and motivated by continuous learning.
I am passionate about Data Science and anything related to technology. Currently, I'm working as a Portafolio Monitoring Intern at Interbank where I've learning a lot of data management "



  descripe_l2_person: "🎯 My goal is to develop my professional career in the data science field, being part of a company that allows me to apply everything I
   have learned so far and continue to grow both personally and professionally to achieve the best results."
  skills:
    - name: Python
      percentage: 90
    - name: Tableau
      percentage: 85
    - name: SQL
      percentage: 80
    - name: Machine learning
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "Interbank"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Portafolio Monitoring Intern"
      startdate: Jul 2021
      enddate: present
      featuredpoints:
        - point: Monitoring the product portofolio using risk index
        - point: Manipulate data to generate insights by Dashboards
        - point: Build a Credit Scoring model to know the profile of the defaults customers

  # Education
  disable_education: false
  education:
    - degree: "B. Economics"
      branch: "Social Sciences"
      university: "Pontifical Catholic University of Peru"
      startedyear: "2017"
      graduation: "2022"
    

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Big Data Certified Associate (BDCA)
      description: International Capatitation in the Bid Data Framework
      img: /images/certi-bigdata.jpg
      url: https://drive.google.com/file/d/1X3RXeXSrel8xloeXrXb9ddq9a93PzuAb/view?usp=sharing
    - title: Machine Learning Explainibility Course
      description: Techniques to extract the following insights from sophisticated machine learning models 
      img: /images/Machine_Learning_Explainability.png
      url: https://drive.google.com/file/d/1MzT4RZyM1pCZqBXidroCGn9-3UocD2ad/view?usp=sharing
    - title: Innovation Challenge Participation
      description: We are developed a product which can help to activate the tourism after the Pandemic
      img: /images/innovation.jpg
      url: https://drive.google.com/file/d/1Zxuc749TeMwGLuf79wmcPfozh2XcWKrd/view?usp=sharing
    - title: Scrum Workshop
      description: Training in agile methodologies
      img: /images/sinerges.jpg
      url: https://drive.google.com/file/d/1sPsSqX7O9eaPE-ahDDGx0wkBcKosfnvt/view?usp=sharing
    

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "example@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
